### ISSUE TITLE
Get the RSSI of a device through the MAC Address

### ISSUE THREAD

**Issue by Paliverse** [nefarius/Nefarius.Utilities.Bluetooth#2]
As the title suggests, info on a particular device by mac address can be useful

**Comment by nefarius** [comment]
OK after doing some research on this topic, this might be a dead-end and not worth it. [See this comment](http://disq.us/p/2r4udul) (screenshot below because for some reason DISQUS direct links just suck and do not direct link at all...).

![image](https://github.com/nefarius/Nefarius.Utilities.Bluetooth/assets/286631/1ac05165-3a00-447c-82fa-dd3df070578f)

I can replicate the behaviour myself easily, especially with the DualSense:

![image](https://github.com/nefarius/Nefarius.Utilities.Bluetooth/assets/286631/06cf1821-60e3-4efe-9084-05292e616f9f)
